# Generated by Django 2.1.7 on 2019-02-25 15:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('uploadapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Upload',
            new_name='UploadModel',
        ),
    ]
